### ISSUE TITLE
Crits

### ISSUE THREAD

**Issue by XaserAcheron** [XaserAcheron/damnums#10]
This goes in the "maybe" bucket. Need to define what exactly a "crit" means, since "theoretically maximum damage per shot" is a bit boring.

**Comment by MajorCooke** [comment]
Not doable with the default damage system. There's no way to retrieve the pre-modified damage at all, thus no retrieving the highest end of the damage. Let's not forget there's also the DamageFunction which lets modders set up things like:

`16+random(1,8)*random(1,8)`

If anything, this would have to invoke something of an API. There is a way to check and see if such an entity exists:

```String nameToCheck = "SomeNameToCheck";
Class<Actor> checker = nameToCheck;
if (checker != null)
{
    // It exists.
}```

But this will have to be done on the modder's end in order to hook into it.

**Comment by XaserAcheron** [comment]
Yeah, going that route would be hackland. With projectiles, it would probably be possible to check the default Damage and blatantly assume that if you do Damage-times-eight, you've got a crit... but that of course excludes DamageFunction, and good luck making anything of that sort work with A_FireBullets. :P

But nah, even if it were feasible, that'd be a pretty boring way to do it anyway. For the most part this issue exists because someone suggested crits and I wanted an idea bucket for answering the question "how should we define a 'crit'?" -- there may not be a satisfactory answer in the end, in which case this gets [No]'d. :P

**Comment by MajorCooke** [comment]
Well, we could allow others an API of sorts as a potential expansion -- but as part of the base itself, it's beyond the scope of this, I'd say.

**Comment by XaserAcheron** [comment]
That's not an avenue I'm particularly interested in exploring, frankly. At least not without some external interest in it.

I won't close this yet, though, just in case a fridge epiphany happens.

**Comment by XaserAcheron** [comment]
Fridges be damned.
