### ISSUE TITLE
Shotgun Spray mode causes damnums to spawn high up when a monster dies

### ISSUE THREAD

**Issue by OrdinaryMagician** [XaserAcheron/damnums#30]
I'm pretty sure this is caused by multiplying the spawn height by 4, which is no longer needed now that WorldThingDamaged happens before the monster height is reduced.

**Comment by XaserAcheron** [comment]
Huh, did the event ordering change? That might allow me to simplify things in general since a bunch of the code in the mod is there to compensate for the fact that WorldThingDamaged happened after death.

Still a bit of a surprise though. I basically have to break compatibility with older versions to fix this.

**Comment by XaserAcheron** [comment]
Yeah, sure enough: https://github.com/coelckers/gzdoom/pull/480

The ordering is sensible now, but isn't this what the script versioning system is for? 9_6
